require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'leanplumDemo' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'leanplumDemoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'leanplumDemo-tvOS' do
  # Pods for leanplumDemo-tvOS

  target 'leanplumDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

dynamic_frameworks = ['Leanplum-iOS-SDK']
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  installer.pod_targets.each do |pod|
      if dynamic_frameworks.include?(pod.name)
        puts "Setting dynamic linking for #{pod.name}"
        def pod.build_type;
          Pod::BuildType.dynamic_framework
        end
      end
    end
end